// huaynos.js - Versión 1.0.2
export const baseDeHuaynos = {
    "1": { titulo: "Ayer la vi a mi ex", artista: "Banda Jazz Perú Sunicancha", tonalidad: "La menor", videoId: "FTV-9T8b05I", inicio: 29 },
    "2": { titulo: "Brindaré Por Ti", artista: "Banda Show La Huaranchal", tonalidad: "La menor", videoId: "JfLWXhriLik", inicio: 577 },
    "3": { titulo: "Cajamarquina", artista: "Banda Perú Armonía y Clase (PAC)", tonalidad: "La menor", videoId: "zRM5JhjWxIA", inicio: 16 },
    "4": { titulo: "Cáncer de Amor", artista: "Banda Show La Huaranchal", tonalidad: "La menor", videoId: "YuEvQ1O1qTU", inicio: 252 },
    "5": { titulo: "Chico Mentiroso", artista: "Banda Nueva Expresión Pomapata", tonalidad: "La menor", videoId: "I69F7OT1Jwg", inicio: 340 },
    "6": { titulo: "Chofercito Carretero", artista: "Banda Show La Huaranchal", tonalidad: "La menor", videoId: "W9h5L96FnWo", inicio: 23 },
    "7": { titulo: "Collar de Lágrimas", artista: "Banda Show Filarmónica Star Otuzco", tonalidad: "La menor", videoId: "AaSC5eeHfyU", inicio: 40 },
    "8": { titulo: "Don Mario", artista: "Tradicional", tonalidad: "La menor", videoId: null, inicio: 0 },
    "9": { titulo: "Dos Más Por Favor", artista: "Banda Nueva Expresión Pomapata", tonalidad: "La menor", videoId: "I69F7OT1Jwg", inicio: 580 },
    "10": { titulo: "En Soledad", artista: "Banda Centro Musical Pomapata", tonalidad: "La menor", videoId: "6DF8IyenqVU", inicio: 0 },
    "11": { titulo: "Hualaycho Bandido", artista: "Banda Súper Brass", tonalidad: "La menor", videoId: "J8KgV4cDCvs", inicio: 19 },
    "12": { titulo: "Madre", artista: "Banda Son Perú", tonalidad: "La menor", videoId: "9_-Go4N2iiI", inicio: 41 },
    "13": { titulo: "Mala Tú", artista: "Banda Perú Armonía y Clase (PAC)", tonalidad: "La menor", videoId: "uigYOd4EwY4", inicio: 204 },
    "14": { titulo: "Me Marcharé", artista: "Banda Santa Cecilia Carabamba", tonalidad: "La menor", videoId: "SYQcSo02J0w", inicio: 29 },
    "15": { titulo: "Mi Barrio La Soledad", artista: "Banda Nueva Expresión Pomapata", tonalidad: "La menor", videoId: "I69F7OT1Jwg", inicio: 18 },
    "16": { titulo: "Mix Flor Pileña", artista: "Varios", tonalidad: "La menor", videoId: null, inicio: 0 },
    "17": { titulo: "No Se Puede Morir de Amor", artista: "Banda Show La Nueva Huaranchal", tonalidad: "La menor", videoId: "bomfZf_7GgQ", inicio: 22 },
    "18": { titulo: "Otra Vez Me Enamoré", artista: "Banda Monumental de Otuzco", tonalidad: "La menor", videoId: "PLm37Vp6G34", inicio: 70 },
    "19": { titulo: "Pocos Minutos", artista: "Banda Orquesta Corazón de Huandoval", tonalidad: "La menor", videoId: "g54QPheDL8M", inicio: 23 },
    "20": { titulo: "Por el Chiquito", artista: "Banda Jazz Perú Sunicancha", tonalidad: "La menor", videoId: "jrnCtIbc6_E", inicio: 189 },
    "47": { titulo: "Ábreme La Puerta", artista: "Banda Orquesta Social Huancaya (BOSH)", tonalidad: "Re menor", videoId: "Pl7GewQdlhg", inicio: 24 },
    "48": { titulo: "Amor Por Internet", artista: "Banda Orquesta Corazón de Huandoval", tonalidad: "Re menor", videoId: "A8LRNb7pz8E", inicio: 23 },
    "49": { titulo: "Cajamarquina", artista: "Banda Show La Huaranchal", tonalidad: "Re menor", videoId: null, inicio: 0 },
    "50": { titulo: "Capitalina", artista: "Banda Show La Huaranchal", tonalidad: "Re menor", videoId: null, inicio: 0 },
    "51": { titulo: "Como Duele el Corazón", artista: "Banda Show La Huaranchal", tonalidad: "Re menor", videoId: "gJ7axr_iHqM", inicio: 347 },
    "52": { titulo: "El Coche de su Madre", artista: "Banda Show La Huaranchal", tonalidad: "Re menor", videoId: "Ulqak7ViLb0", inicio: 111 },
    "53": { titulo: "La Proforma", artista: "Banda Show Espectáculo Quivilla", tonalidad: "Re menor", videoId: "-rX5D7HEjNI", inicio: 550 },
    "54": { titulo: "Lloro Por Tu Amor", artista: "Banda Show La Huaranchal", tonalidad: "Re menor", videoId: "XZbuk64FDMI", inicio: 0 },
    "55": { titulo: "Márchate", artista: "Banda Show Espectáculo Quivilla", tonalidad: "Re menor", videoId: "MO8Ctj3oC9E", inicio: 23 },
    "56": { titulo: "Mujer Carhuacina", artista: "Banda Monumental de Huaraz", tonalidad: "Re menor", videoId: "kBvo6XCM_ug", inicio: 557 }
    // ... continúa con los huaynos restantes (21-46, 57-81) cuando tengas los datos
};