// huaynos.js - Versión 1.0.2
export const baseDeHuaynos = {
    "1":  { titulo: "Ayer la vi a mi ex",           artista: "Banda Jazz Perú Sunicancha",                  tonalidad: "La menor", videoId: "FTV-9T8b05I", inicio: 29 },
    "2":  { titulo: "Brindaré Por Ti",              artista: "Banda Show La Huaranchal",                    tonalidad: "La menor", videoId: "JfLWXhriLik", inicio: 577 },
    "3":  { titulo: "Cajamarquina",                 artista: "Banda Perú Armonía y Clase (PAC)",            tonalidad: "La menor", videoId: "zRM5JhjWxIA", inicio: 16 },
    "4":  { titulo: "Cáncer de Amor",               artista: "Banda Show La Huaranchal",                    tonalidad: "La menor", videoId: "YuEvQ1O1qTU", inicio: 252 },
    "5":  { titulo: "Chico Mentiroso",              artista: "Banda Nueva Expresión Pomapata",              tonalidad: "La menor", videoId: "I69F7OT1Jwg", inicio: 340 },
    "6":  { titulo: "Chofercito Carretero",         artista: "Banda Show La Huaranchal",                    tonalidad: "La menor", videoId: "W9h5L96FnWo", inicio: 23 },
    "7":  { titulo: "Collar de Lágrimas",           artista: "Banda Show Filarmónica Star Otuzco",          tonalidad: "La menor", videoId: "AaSC5eeHfyU", inicio: 40 },
    "8":  { titulo: "Don Mario",                    artista: null,                                          tonalidad: "La menor", videoId: null, inicio: 0 },
    "9":  { titulo: "Dos Más Por Favor",            artista: "Banda Nueva Expresión Pomapata",              tonalidad: "La menor", videoId: "I69F7OT1Jwg", inicio: 580 },
    "10": { titulo: "En Soledad",                   artista: "Banda Centro Musical Pomapata",               tonalidad: "La menor", videoId: "6DF8IyenqVU", inicio: 0 },
    "11": { titulo: "Hualaycho Bandido",            artista: "Banda Súper Brass",                           tonalidad: "La menor", videoId: "J8KgV4cDCvs", inicio: 19 },
    "12": { titulo: "Madre",                        artista: "Banda Son Perú",                              tonalidad: "La menor", videoId: "9_-Go4N2iiI", inicio: 41 },
    "13": { titulo: "Mala Tú",                      artista: "Banda Perú Armonía y Clase (PAC)",            tonalidad: "La menor", videoId: "uigYOd4EwY4", inicio: 204 },
    "14": { titulo: "Me Marcharé",                  artista: "Banda Santa Cecilia Carabamba",               tonalidad: "La menor", videoId: "SYQcSo02J0w", inicio: 29 },
    "15": { titulo: "Mi Barrio La Soledad",         artista: "Banda Nueva Expresión Pomapata",              tonalidad: "La menor", videoId: "I69F7OT1Jwg", inicio: 18 },
    "16": { titulo: "Mix Flor Pileña",              artista: null,                                          tonalidad: "La menor", videoId: null, inicio: 0 },
    "17": { titulo: "No Se Puede Morir de Amor",    artista: "Banda Show La Nueva Huaranchal",              tonalidad: "La menor", videoId: "bomfZf_7GgQ", inicio: 22 },
    "18": { titulo: "Otra Vez Me Enamoré",          artista: "Banda Monumental de Otuzco",                  tonalidad: "La menor", videoId: "PLm37Vp6G34", inicio: 70 },
    "19": { titulo: "Pocos Minutos",                artista: "Banda Orquesta Corazón de Huandoval",         tonalidad: "La menor", videoId: "g54QPheDL8M", inicio: 23 },
    "20": { titulo: "Por el Chiquito",              artista: "Banda Jazz Perú Sunicancha",                  tonalidad: "La menor", videoId: "jrnCtIbc6_E", inicio: 189 },
    "26": { titulo: "A Los Filos De Un Cuchillo",   artista: "Banda Show La Huaranchal",                    tonalidad: "Mi menor", videoId: "AA7wKyslXo0", inicio: 230 },
    "27": { titulo: "Busco un Amor",                artista: "Banda Centro Musical Pomapata",               tonalidad: "Mi menor", videoId: "GpcHdt6tSxU", inicio: 16 },
    "28": { titulo: "Déjame",                       artista: null,                                          tonalidad: "Mi menor", videoId: null, inicio: 0 },
    "29": { titulo: "Dos Cervezas Más",             artista: "Banda Nueva Expresión Pomapata",              tonalidad: "Mi menor", videoId: "wXtriwE3OXw", inicio: 16 },
    "30": { titulo: "El Amor de mi Vida",           artista: "Banda Orquesta JJ Show",                      tonalidad: "Mi menor", videoId: "RSfG7B_Bs40", inicio: 32 },
    "31": { titulo: "Hay Niveles",                  artista: "Banda Show La Huaranchal",                    tonalidad: "Mi menor", videoId: "JfLWXhriLik", inicio: 37 },
    "32": { titulo: "La Cadena Se Rompió",          artista: "Banda Show La Huaranchal",                    tonalidad: "Mi menor", videoId: "CfD_i6oP7SE", inicio: 23 },
    "33": { titulo: "Linda Andahuaylina",           artista: "Banda Show Sinfónica Sunicancha",             tonalidad: "Mi menor", videoId: "1LCDzUq_FQM", inicio: 4 },
    "34": { titulo: "Linda Huaracina",              artista: "Banda Show Filarmónica Llipa",                tonalidad: "Mi menor", videoId: "61L6WUdSI34", inicio: 39 },
    "35": { titulo: "Mujer Carhuacina",             artista: "Banda Show La Huaranchal",                    tonalidad: "Mi menor", videoId: "KH2mZ1yqwjY", inicio: 133 },
    "36": { titulo: "Pájaro Pájaro Pájaro",         artista: "Banda Internacional Santa Cecilia de Cátac",  tonalidad: "Mi menor", videoId: "UyTd7c-rpEI", inicio: 47 },
    "37": { titulo: "Perdóname",                    artista: "Banda Show La Huaranchal",                    tonalidad: "Mi menor", videoId: "LxQn8yEj0_g", inicio: 31 },
    "38": { titulo: "Por Que Me Dices Que Te Vas",  artista: "Banda Filarmónica Star Sayan",                tonalidad: "Mi menor", videoId: "3FkTXhdiCD0", inicio: 17 },
    "39": { titulo: "Puente de Marcará",            artista: "Banda Show La Huaranchal",                    tonalidad: "Mi menor", videoId: "KH2mZ1yqwjY", inicio: 0 },
    "40": { titulo: "Que Linda Flor",               artista: null,                                          tonalidad: "Mi menor", videoId: null, inicio: 0 }, 
    "41": { titulo: "Rio Santa",                    artista: "Banda Star Pomapata",                         tonalidad: "Mi menor", videoId: "bnZrU9lUaRk", inicio: 6 },
    "42": { titulo: "Rosaura Lindaura",             artista: "Banda Show La Nueva Huaranchal",              tonalidad: "Mi menor", videoId: "4MENUlUsDyM", inicio: 20 },
    "43": { titulo: "Tomaré Para Olvidarte",        artista: "Banda Nueva Expresión Pomapata",              tonalidad: "Mi menor", videoId: "wXtriwE3OXw", inicio: 253 },
    "44": { titulo: "Un Domingo Yo La Vi",          artista: "Banda Orquesta Social Huancaya (BOSH)",       tonalidad: "Mi menor", videoId: "w9ivCkukPqc", inicio: 91 },
    "45": { titulo: "Valicha",                      artista: "Banda de la Marina de Guerra del Perú",       tonalidad: "Mi menor", videoId: "-hk3YrkVt5I", inicio: 37 },
    "46": { titulo: "Yo Nací Solo Para Ti",         artista: "Banda Centro Musical Pomapata",               tonalidad: "Mi menor", videoId: "iGo-vGi5L8g", inicio: 15 },
    "47": { titulo: "Ábreme La Puerta",             artista: null,                                          tonalidad: "Re menor", videoId: null, inicio: 0 },
    "48": { titulo: "Amor Por Internet",            artista: "Banda Orquesta Corazón de Huandoval",         tonalidad: "Re menor", videoId: "A8LRNb7pz8E", inicio: 23 },
    "49": { titulo: "Cajamarquina",                 artista: null,                                          tonalidad: "Re menor", videoId: null, inicio: 0 },
    "50": { titulo: "Capitalina",                   artista: null,                                          tonalidad: "Re menor", videoId: null, inicio: 0 },
    "51": { titulo: "Como Duele el Corazón",        artista: "Banda Show La Huaranchal",                    tonalidad: "Re menor", videoId: "gJ7axr_iHqM", inicio: 347 },
    "52": { titulo: "El Coche de su Madre",         artista: "Banda Show La Huaranchal",                    tonalidad: "Re menor", videoId: "Ulqak7ViLb0", inicio: 111 },
    "53": { titulo: "La Proforma",                  artista: "Banda Show Espectáculo Quivilla",             tonalidad: "Re menor", videoId: "-rX5D7HEjNI", inicio: 550 },
    "54": { titulo: "Lloro Por Tu Amor",            artista: "Banda Show La Huaranchal",                    tonalidad: "Re menor", videoId: "XZbuk64FDMI", inicio: 0 },
    "55": { titulo: "Márchate",                     artista: "Banda Show Espectáculo Quivilla",             tonalidad: "Re menor", videoId: "-rX5D7HEjNI", inicio: 550 },
    "56": { titulo: "Me Estás Sacando La Vuelta",   artista: "Banda Monumental de Huaraz",                  tonalidad: "Re menor", videoId: "kBvo6XCM_ug", inicio: 557 },
    "57": { titulo: "Mujer Carhuacina",             artista: null,                                          tonalidad: "Re menor", videoId: null, inicio: 0 },
    "58": { titulo: "No Me Preguntes Por Ella",     artista: null,                                          tonalidad: "Re menor", videoId: null, inicio: 0 },
    "59": { titulo: "Pásame La Cerveza",            artista: "Banda Show La Huaranchal",                    tonalidad: "Re menor", videoId: "MO8Ctj3oC9E", inicio: 23 },
    "60": { titulo: "Por Ti",                       artista: "Banda Show Espectáculo Quivilla",             tonalidad: "Re menor", videoId: "kBvo6XCM_ug", inicio: 557 },
    "61": { titulo: "Soledad",                      artista: "Banda Orquesta Social Huancaya (BOSH)",       tonalidad: "Re menor", videoId: "cV5ZcytWfJ8", inicio: 328 },
    "62": { titulo: "Todo Empezó Como Jugando",     artista: null,                                          tonalidad: "Re menor", videoId: null, inicio: 0 },
    "63": { titulo: "Un Domingo Yo La Vi",          artista: null,                                          tonalidad: "Re menor", videoId: null, inicio: 0 },
    "64": { titulo: "Amigo",                        artista: "Banda Show La Huaranchal",                    tonalidad: "Sol menor", videoId: "jJbEQOOQqn8", inicio: 274 },
    "65": { titulo: "Aquella Tarde",                artista: "Banda Show La Huaranchal",                    tonalidad: "Sol menor", videoId: "eA78y4wZUBE", inicio: 332 },
    "66": { titulo: "Brindaré Por Ti",              artista: "Banda Centro Musical Pomapata",               tonalidad: "Sol menor", videoId: "0pWfOLv1FqM", inicio: 66 }, 
    "67": { titulo: "Chofercito Carretero",         artista: "Banda Jazz Perú Sunicancha",                  tonalidad: "Sol menor", videoId: "daXIQNGP7JU", inicio: 156 },
    "68": { titulo: "Don Mario",                    artista: "Banda Orquesta Corazón de Huandoval",         tonalidad: "Sol menor", videoId: "-B_8EaVfc5w", inicio: 465 },
    "69": { titulo: "Hay Niveles",                  artista: null,                                          tonalidad: "Sol menor", videoId: null, inicio: 0 },
    "70": { titulo: "La Cadena Se Rompió",          artista: "Banda Orquesta Social Huancaya (BOSH)",       tonalidad: "Sol menor", videoId: "6n34Gtn89C4", inicio: 167 },
    "71": { titulo: "La Chismosa",                  artista: "Banda Orquesta Social Huancaya (BOSH)",       tonalidad: "Sol menor", videoId: "jrok1Lz5-bc", inicio: 0 },
    "72": { titulo: "Madre",                        artista: "Banda Papá Los Herederos Sunicancha",         tonalidad: "Sol menor", videoId: "SQoYQt79FoY", inicio: 23 },
    "73": { titulo: "Mary Se Llama",                artista: "Banda Show La Huaranchal",                    tonalidad: "Sol menor", videoId: "9sYfgALM4IU", inicio: 62 },
    "74": { titulo: "Me Emborracho por tu Amor",    artista: "Banda Show La Huaranchal",                    tonalidad: "Sol menor", videoId: "cglPEIAJo1k", inicio: 29 },
    "75": { titulo: "Mix Flor Piña",                artista: null, tonalidad: "Sol menor", videoId: null, inicio: 0 },
    "76": { titulo: "No Puedo Amarte",              artista: null, tonalidad: "Sol menor", videoId: null, inicio: 0 },
    "77": { titulo: "Otra Vez Me Enamoré",          artista: null, tonalidad: "Sol menor", videoId: null, inicio: 0 },
    "78": { titulo: "Que Linda Flor",               artista: null, tonalidad: "Sol menor", videoId: null, inicio: 0 },
    "79": { titulo: "Viaje de Amor",                artista: "Banda Orquesta Corazón de Huandoval",         tonalidad: "Sol menor", videoId: "MPIBKts3HCE", inicio: 20 },
    "80": { titulo: "Vizcachita",                   artista: null, tonalidad: "Sol menor", videoId: null, inicio: 0 },
    "81": { titulo: "Ya Se Marchó",                 artista: "Banda Show La Huaranchal", tonalidad: "Sol menor", videoId: "5aM1V9y_alk", inicio: 252 }
};